Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -39,7 +39,18 @@ jobs:
       with:
         node-version: ${{ env.NODE_VERSION }}
         cache: 'npm'
-
+        
+    - name: Show npm config list
+      run: npm config list
+    - run: '[ -z "$NODE_AUTH_TOKEN" ] && echo "Token missing" || echo "Token present"'
+    - run: 'echo "Token length: ${#NODE_AUTH_TOKEN}"'
+    - name: Show npm config locations
+      run: npm config get userconfig && npm config get globalconfig
+    - name: List .npmrc files
+      run: |
+        ls -al $HOME/.npmrc || echo "No .npmrc in home"
+        ls -al .npmrc || echo "No .npmrc in repo"
+    
     - name: Install Dependencies
       run: npm ci
       env:
